version: "3.9"
services:
  mongo:
    image: mongo:5.0.5
    ports:
      - "27017:27017"
    container_name: mongo
    hostname: mongo

  api:
    image: k-events-api:1.0.0
    container_name: api
    hostname: api
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      - MONGO_DB_NAME=events
      - MONGO_DB_HOST=mongo
      - MONGO_DB_PORT=27017
    links:
      - mongo

  app:
    image: k-events-app:1.0.0
    container_name: app
    hostname: app
    depends_on:
      - api
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=api
    links:
      - api