name: API CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build project with Maven
        run: mvn clean install -f k-events-api/pom.xml

  build_docker_image:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: [ build_and_test ]
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PWD }}
      - name: Build image
        run: docker build -t k-events-api:1.0.0 -f Dockerfile_API .
      - name: Tag
        run: docker tag k-events-api:1.0.0 ${{ secrets.DOCKER_REPO }}/k-events-api:1.0.0
      - name: Publish
        run: docker push ${{ secrets.DOCKER_REPO }}/k-events-api:1.0.0